### ISSUE TITLE
Dynamic workflow creation

### ISSUE THREAD

**Issue by dpavlikovskiy** [eternita/workflow#8]
Create a demo how to create / load / execute workflow during runtime

**Comment by jreimone** [comment]
I'm very looking forward to the demo.

**Comment by dpavlikovskiy** [comment]
Here is example how to create simplest HelloWorld workflow in java

https://github.com/eternita/workflow/blob/master/neuro4j-workflow-core/src/test/java/org/neuro4j/flows/example/HelloWorldTest.java#L111

`
//StartNode1 -> CustomNode(o.n.f.e.HelloWorld) -> EndNode

	Workflow workflow = new WorkflowBuilder("org.neuro4j.flows.HelloWorld", "StartNode1")
				                .addCustomNode("org.neuro4j.flows.example.HelloWorld")
				                      .withOnError(createEndNode()).done()
				                .addEndNode()      
				                .build();
....

ExecutionResult result = engine.execute(workflow, "StartNode1", request);

`
